ci:
  autoupdate_commit_msg: 'ci: pre-commit autoupdate'
  autofix_commit_msg: 'ci: pre-commit autofix'

repos:
-   repo: local
    hooks:
    -   id: check-yaml
        name: check-yaml
        entry: python -m pre_commit.hooks.check_yaml
        language: system
        types: [yaml]
        exclude: '^docs/specs/'

    -   id: end-of-file-fixer
        name: end-of-file-fixer
        entry: python -m pre_commit.hooks.end_of_file_fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
        
    -   id: trailing-whitespace
        name: trailing-whitespace
        entry: python -m pre_commit.hooks.trailing_whitespace_fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
        
    -   id: check-added-large-files
        name: check-added-large-files
        entry: python -m pre_commit.hooks.check_added_large_files
        language: system
        stages: [commit, push, manual]
        
    -   id: check-case-conflict
        name: check-case-conflict
        entry: python -m pre_commit.hooks.check_case_conflict
        language: system
        stages: [commit, push, manual]
        
    -   id: check-merge-conflict
        name: check-merge-conflict
        entry: python -m pre_commit.hooks.check_merge_conflict
        language: system
        stages: [commit, push, manual]
        
    -   id: debug-statements
        name: debug-statements
        entry: python -m pre_commit.hooks.debug_statement_hook
        language: system
        types: [python]
        stages: [commit, push, manual]
        
    -   id: detect-private-key
        name: detect-private-key
        entry: python -m pre_commit.hooks.detect_private_key
        language: system
        types: [text]
        stages: [commit, push, manual]

    -   id: ruff
        name: ruff
        description: Run Ruff linter
        entry: ruff check
        language: system
        types: [python]
        args: [--fix, --exit-non-zero-on-fix]
        stages: [commit, push, manual]

    -   id: ruff-format
        name: ruff-format
        description: Run Ruff formatter
        entry: ruff format
        language: system
        types: [python]
        stages: [commit, push, manual]

    -   id: isort
        name: isort
        description: Sort imports
        entry: isort
        language: system
        types: [python]
        args: ["--profile", "black"]
        stages: [commit, push, manual]

    -   id: mypy
        name: mypy
        description: Run mypy static type checker
        entry: mypy
        language: system
        types: [python]
        exclude: '^tests/|^config/scripts/|^examples/'
        stages: [commit, push, manual]

    -   id: bandit
        name: bandit
        description: Check for security issues
        entry: bandit -c pyproject.toml
        language: system
        types: [python]
        exclude: '^tests/|^examples/'
        stages: [commit, push, manual]

    -   id: docformatter
        name: docformatter
        description: Format docstrings
        entry: docformatter --in-place --config ./pyproject.toml
        language: system
        types: [python]
        stages: [commit, push, manual]

    -   id: interrogate
        name: interrogate
        description: Check docstring coverage
        entry: interrogate -c pyproject.toml --ignore-init-method
        language: system
        types: [python]
        exclude: '^tests/|^examples/|^config/scripts/'
        stages: [commit, push, manual]

    -   id: poetry-check
        name: poetry-check
        description: Check the Poetry configuration
        entry: poetry check
        language: system
        pass_filenames: false
        files: ^pyproject.toml$
        stages: [commit, push, manual]