ci:
  # Skip pre-commit fetch operations during commit
  autoupdate_commit_msg: 'ci: pre-commit autoupdate'
  autofix_commit_msg: 'ci: pre-commit autofix'
  skip: [ruff, ruff-format, isort, mypy, bandit, docformatter, interrogate]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key

# All other hooks temporarily disabled to avoid fetch issues
# Uncomment below when git connectivity is available

#-   repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.0.292
#    hooks:
#    -   id: ruff
#        args: [--fix, --exit-non-zero-on-fix]
#    -   id: ruff-format
#        args: [--preview]
#
#-   repo: https://github.com/pycqa/isort
#    rev: 5.12.0
#    hooks:
#    -   id: isort
#        args: ["--profile", "black"]
#
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.5.1
#    hooks:
#    -   id: mypy
#        additional_dependencies: [
#            "types-requests",
#            "types-PyYAML",
#            "pydantic>=2.0.0",
#            "sqlalchemy>=2.0.0",
#            "types-setuptools",
#        ]
#
#-   repo: https://github.com/pycqa/bandit
#    rev: 1.7.5
#    hooks:
#    -   id: bandit
#        args: ["-c", "pyproject.toml"]
#        additional_dependencies: ["bandit[toml]"]
#        exclude: "tests/"
#
#-   repo: https://github.com/PyCQA/docformatter
#    rev: v1.7.5
#    hooks:
#    -   id: docformatter
#        args: ["--in-place", "--config", "./pyproject.toml"]
#
#-   repo: https://github.com/charliermarsh/interrogate
#    rev: 1.5.0
#    hooks:
#    -   id: interrogate
#        args: ["-c", "pyproject.toml", "--ignore-init-method"]
#
#-   repo: https://github.com/python-poetry/poetry
#    rev: 1.6.1
#    hooks:
#    -   id: poetry-check
#    -   id: poetry-lock
