name: Container Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 3'  # Weekly on Wednesday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-scan:
    name: Build and Scan Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./config/Dockerfile
          push: false
          load: true
          tags: ztoq:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
